spring:
  profiles:
    active:
      - dev

---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client  #微服务名字
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud01?serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yidu.springcloud.entity

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microServiceCloud-dept8001 #自定义服务器名称信息(取别名)
    prefer-ip-address: true #访问地址可以显示id地址

#在该微服务中添加信息的描述
info:
  app.name: yidu-microServiceCloud
  company.name: www.yidu.com
  build.artifactId:  @project.artifactId@
  build.version: @project.version@

---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client  #微服务名字
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud02?serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yidu.springcloud.entity

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microServiceCloud-dept8001 #自定义服务器名称信息(取别名)
    prefer-ip-address: true #访问地址可以显示id地址

#在该微服务中添加信息的描述
info:
  app.name: yidu-microServiceCloud
  company.name: www.yidu.com
  build.artifactId:  @project.artifactId@
  build.version: @project.version@